from windows import WindowsLocalClient
from mac import MacLocalClient
import platform, sys, pickle
from galaxy.api.plugin import create_and_run_plugin
from consts import GameID, LOCAL_FILE_CACHE, GAME_TIME_CACHE_KEY, logger
from galaxy.api.plugin import Plugin
from galaxy.api.consts import LicenseType, OSCompatibility, Platform
from galaxy.api.types import Authentication, Game, LicenseInfo
from galaxyutils.time_tracker import GameNotTrackedException, TimeTracker


class RiotPlugin(Plugin):
    def __init__(self, reader, writer, token):
        super().__init__(
            Platform.RiotGames,  # choose platform from available list
            "0.1.3",  # version
            reader,
            writer,
            token,
        )
        self.game_time_cache = None
        plat = platform.system().lower()
        classes = {"windows": WindowsLocalClient, "darwin": MacLocalClient}
        self.local = classes[plat]()

    async def shutdown(self):
        await self.local.shutdown()
        if self.game_time_cache:
            file = open(LOCAL_FILE_CACHE, "w+")
            file.write("# DO NOT EDIT THIS FILE (pretty pls)\n")
            file.write(self.game_time_tracker.get_time_cache_hex())
            file.close()
        await super().shutdown()

    async def authenticate(self, stored_credentials=None):
        self.store_credentials({"dummy": "dummy"})
        return Authentication("riot_user", "Riot User")

    async def get_owned_games(self):
        logger.info("Getting owned games")
        return [
            Game(
                GameID.league_of_legends,
                "League of Legends",
                None,
                LicenseInfo(LicenseType.FreeToPlay),
            ),
            Game(
                GameID.legends_of_runeterra,
                "Legends of Runeterra",
                None,
                LicenseInfo(LicenseType.FreeToPlay),
            ),
            Game(
                GameID.valorant,
                "Valorant",
                None,
                LicenseInfo(LicenseType.FreeToPlay),
            ),
        ]

    async def get_os_compatibility(self, game_id, context):
        logger.info("Getting os compatibility")
        if game_id == GameID.league_of_legends:
            return OSCompatibility.Windows | OSCompatibility.MacOS
        elif game_id == GameID.legends_of_runeterra:
            return OSCompatibility.Windows
        elif game_id == GameID.valorant:
            return OSCompatibility.Windows
        else:
            return

    def handshake_complete(self):
        if GAME_TIME_CACHE_KEY in self.persistent_cache:
            self.game_time_cache = pickle.loads(
                bytes.fromhex(self.persistent_cache[GAME_TIME_CACHE_KEY])
            )
        else:
            try:
                file = open(LOCAL_FILE_CACHE, "r")
                for line in file.readlines():
                    if line[:1] != "#":
                        self.game_time_cache = pickle.loads(bytes.fromhex(line))
                        break
                file.close()
            except FileNotFoundError:
                self.game_time_tracker = TimeTracker()
                return
        self.game_time_tracker = TimeTracker(
            game_time_cache=self.game_time_cache
        )

    def game_times_import_complete(self):
        self.game_time_cache = self.game_time_tracker.get_time_cache_hex()
        self.persistent_cache[
            GAME_TIME_CACHE_KEY
        ] = self.game_time_tracker.get_time_cache_hex()
        self.push_cache()

    async def get_game_time(self, game_id, context):
        try:
            time = self.game_time_tracker.get_tracked_time(game_id)
        except GameNotTrackedException:
            time = None
        return time

    async def get_local_games(self):
        return self.local.get_local_games()

    async def uninstall_game(self, game_id):
        return self.local.uninstall_game()

    async def install_game(self, game_id):
        return self.local.install_game()

    async def launch_game(self, game_id):
        return self.local.launch_game()

    def tick(self):
        self.local.tick(
            self.update_local_game_status,
            self.game_time_tracker.start_tracking_game,
            self.game_time_tracker.stop_tracking_game,
            self.create_task,
        )


def main():
    create_and_run_plugin(RiotPlugin, sys.argv)


if __name__ == "__main__":
    main()
